alias update-vscode="wget https://vscode-update.azurewebsites.net/latest/linux-deb-x64/stable -O /tmp/code_latest_amd64.deb && sudo dpkg -i /tmp/code_latest_amd64.deb"
alias j="jump"
alias tcli="/home/grodes/devel/td-360-cli/main.sh"
alias gcd="git checkout development"
alias pitbull="echo \"1, 2, 3 dale\" && git pull"
alias chrome-no-cors="google-chrome --disable-web-security --user-data-dir=\"$HOME/.config/google-chrome\" --allow-file-access-from-files > /dev/null 2>&1 &"
